#+title: roadmap
#+author: Richard Westhaver <ellis@rwest.io>
#+description: The Compiler Company Roadmap
#+setupfile: ../clean.theme
#+filetags: milestone
* 2024
SCHEDULED: <2024-01-01 Mon>--<2024-12-31 Tue>
:PROPERTIES:
:ID:       bef157e2-ef55-4653-9916-1a329255a920
:CREATED:  <2024-08-26 Mon 18:47>
:END:
** WIP migrate VC off of EC2                                  :opsec:vc:code:
:PROPERTIES:
:ID:       e71f5fa6-59de-4c80-9cf8-3345f7310105
:END:
:LOGBOOK:
- State "WIP"        from              [2024-05-06 Mon 16:43]
:END:
We no longer need to maintain an instance of our forge in AWS now that
we have enough compute in-house.

vc.compiler.company will be migrate to rurik on a dedicated pod
(requires ubuntu).
** WIP Wireguard VPN                                              :net:opsec:
:PROPERTIES:
:ID:       867d2bd7-cedc-4695-b98a-57296bae7792
:END:
:LOGBOOK:
- State "TODO"       from              [2024-05-06 Mon 16:48]
- State "WIP"        from "TODO"       [2024-05-06 Mon 16:48]
- Note taken on [2024-08-12 Mon 18:21] \\
  all that is left is to configure for VM and containers
:END:
Wireguard is a fast, secure, and easy to configure VPN library. All
our primary devices have been configured and tested with two available
endpoints. Our goal is to migrate all existing devices, then make
appropriate accomodations for Podman containers, and finally KVM.
** TBD IO                                                              :lisp:
:PROPERTIES:
:ID:       ad563749-b7c1-4d17-8a9d-65361ce8013a
:END:
:LOGBOOK:
- State "TBD"        from              [2024-05-06 Mon 16:50]
:END:
io_uring is the Linux library we have chosen to spend some time
getting comfortable with and for which we've written incomplete Common
Lisp bindings - URING. This library will soon be developed in parallel
to the higher-level IO library - similar to the development of ROCKSDB
and RDB.

Over the next few months our IO ecosystem will slowly expand. As a
short-term goal, we will implement simple binary streams backed by
io_uring.
** WIP skel
:PROPERTIES:
:ID:       34e336b5-66e7-46db-ab65-970131748fe0
:END:
:LOGBOOK:
- State "WIP"        from "TBD"        [2024-05-06 Mon 17:06]
- Note taken on [2024-08-12 Mon 18:21] \\
  makefiles are now replaced by skelfile rules. next step is SKEL-VM for
  optimize rule execution plans.
:END:
The pieces are there, just needs glue.

A usable SKEL system is a top priority for this year. To get there we
need to give love to many of the underlying core libraries too - most
of all =cli=.

The two top priorities are VC commands and implementing a functional
replacement for makefiles as used in the infra project.
** TBD orgdb                                                            :mvp:
:PROPERTIES:
:VERSION:  0.1.0
:ID:       b07a5a1b-93ec-457e-bd50-6b00b9a10352
:END:
:LOGBOOK:
- State "TBD"        from              [2024-08-18 Sun 01:58]
:END:
- similar idea to org-roam
- stored in rocksdb columns
** DONE infra
:PROPERTIES:
:ID:       615dfb29-859c-4ad7-9acf-01ea8aee1174
:END:
:LOGBOOK:
- State "TODO"       from              [2024-05-06 Mon 17:06]
- State "DONE"       from "TODO"       [2024-08-12 Mon 18:23]
:END:
It is time to move away from makefiles and start integrating our own
programs into the system bootstrap process. This iteration of the
infra project will have a few POSIX shell scripts for checking the
host and grabbing a pre-compiled lisp as well as a compressed
=infra.core= image.
* OUTLINE 2025
SCHEDULED: <2025-01-01 Mon>--<2025-12-31 Wed>
:PROPERTIES:
:ID:       93349821-ca20-4c07-a016-fd270c0c3b8d
:END:
:LOGBOOK:
- State "OUTLINE"    from              [2024-08-16 Fri 23:04]
:END:
** TBD orgdb
:PROPERTIES:
:VERSION:  1.0.0
:ID:       09987fe2-7272-4054-b728-e2c87135a8a1
:END:
:LOGBOOK:
- State "TBD"        from              [2024-08-18 Sun 02:00]
:END:
** TBD bbdb
:PROPERTIES:
:VERSION:  0.1.0
:ID:       9426d8b9-fa7b-4515-aa13-54cc45e8358f
:END:
:LOGBOOK:
- State "TBD"        from              [2024-08-18 Sun 02:03]
:END:
