#+title: Research Tasks
#+author: Richard Westhaver
#+email: ellis@compiler.company
#+description: Research task list
#+setupfile: ../../clean.theme
#+OPTIONS: num:nil d:t prop:t toc:t
#+ARCHIVE: ../../archive/plan.org::** core
#+LOCATION: ~/src/
#+filetags: research
* OUTLINE pot of greed
:PROPERTIES:
:ID:       020f0ea3-9584-4d4a-9976-adb8f790ce29
:CREATED:  <2025-01-17 Fri 15:54>
:END:
:LOGBOOK:
- State "OUTLINE"    from              [2025-06-11 Wed 22:41]
:END:
- honeypot
- capture, log, amuse, retaliate
- traffic redirection
* RESEARCH Writing a C Compiler
:PROPERTIES:
:CREATED:  <2024-09-29 Sun 15:57>
:ID:       c898f19a-1699-4ca1-88e4-5fc646e0144b
:END:
:LOGBOOK:
- State "RESEARCH"   from "TODO"       [2024-09-29 Sun 15:57]
:END:
- [[https://www.reddit.com/r/Compilers/comments/i92e8i/i_want_to_build_a_c_compiler_where_to_start/][Reddit - Dive into anything]]
#+begin_quote
"A Retargetable C Compiler" by Hanson -- this details the
implementation of LCC, which is a production grade compiler. It's a
serious resource. Might be a bit too much for a first compiler;

"Practical Compiler Construction" by Nils M Holms -- haven't read this
one, but his work seems OK, if a bit idiosyncratic;

"Modern Compiler Implementation in C" by Andrew Appel -- a good
resource, but the code might be non-idiomatic C and hard to follow
since it's translated from the ML version of the book (I've only read
the Java version, and the code is kind of bad).

There's also Wirth's "Compiler Construction", which introduces you to
a no nonsense compiler for Oberon. It's not C, but you can change it
quite easily.
#+end_quote
- [[https://norasandler.com/2017/11/29/Write-a-Compiler.html][Writing a C Compiler, Part 1]]
- [[https://github.com/DoctorWkt/acwj][GitHub - DoctorWkt/acwj: A Compiler Writing Journey]]
- [[https://github.com/morfishman/Simple_C_Compiler][GitHub - morfishman/Simple_C_Compiler: Simple C compiler that i build for assembler 32 bit]]
- [[https://github.com/drh/lcc][GitHub - drh/lcc: The lcc retargetable ANSI C compiler]]
- [[https://archive.org/details/a-retargetable-c-compiler-design-and-implementation-christopher-w.-fraser-david-r.-hanson-z-lib.org][A Retargetable C Compiler Design And Implementation ( Christopher W. Fraser David R. Hanson) (z Lib.org) : Free Download, Borrow, and Streaming : Internet Archive]]
- [[https://aosabook.org/en/v1/llvm.html#:~:text=LLVM%20is%20a%20Collection%20of,machine%20like%20the%20JVM%20or%20.][The Architecture of Open Source Applications (Volume 1)LLVM]]
- [[https://www.bradrodriguez.com/papers/index.html][Publications - Bradford J. Rodriguez]] - forth
- [[https://vishnudevtj.github.io/notes/assembly-in-emacs][Assembly In Emacs · The Plain Text]]
* RESEARCH podman kvm farm
:PROPERTIES:
:CREATED:  <2024-09-03 Tue 17:46>
:ID:       1e7404e9-6b57-4aec-98cf-81c6328db041
:END:
:LOGBOOK:
- State "RESEARCH"   from "TODO"       [2024-09-03 Tue 17:46]
:END:
[[https://docs.podman.io/en/latest/markdown/podman-farm.1.html][podman-farm — Podman documentation]]
* WIP Curves
:PROPERTIES:
:CREATED:  <2025-05-08 Thu 18:00>
:ID:       63a03922-03bb-47dd-af82-e7274135c0e1
:END:
:LOGBOOK:
- State "WIP"        from              [2025-05-08 Thu 18:00]
:END:
Realistically we may need a dedicated lib/math..

obj doesn't cover all the bases.

SBCL provides the numeric tower via types, we really need a math tower..

- see [[id:1b08ca47-cace-4ce5-a0f2-cd74dcf8c547][math]] and [[id:b515faef-e1dc-4b30-bf50-599b7394e797][tensor]]

** WIP SFC
:PROPERTIES:
:CREATED:  <2025-05-08 Thu 18:01>
:ID:       2578ff0f-c71d-4c9d-89da-ea97a3146156
:END:
:LOGBOOK:
- State "OUTLINE"    from              [2025-05-08 Thu 18:01]
- State "WIP"        from "OUTLINE"    [2025-05-08 Thu 18:01]
:END:
Space-Filling Curves
*** RESEARCH Hilbert Curves
:PROPERTIES:
:CREATED:  <2025-05-07 Wed 16:14>
:ID:       e6e79d8f-5958-4fe2-9380-710c7392423e
:END:
:LOGBOOK:
- State "RESEARCH"   from              [2025-05-07 Wed 16:14]
:END:
- Hilbert R-Trees, X-Tree..
  - X+ Trees? need to see the most recent research and why it hasn't become popular
    - speed?
- persistence?
  - maybe 'generation' is a dimension, Ln is on disk files
* DONE good lisp API docgen
SCHEDULED: <2026-06-10 Wed>
:PROPERTIES:
:ID:       66cbdde4-b73f-4c8b-a023-1b280c227658
:CREATED:  <2025-07-08 Tue 22:40>
:Effort:   5:00
:END:
:LOGBOOK:
- State "RESEARCH"   from              [2025-07-08 Tue 22:40]
CLOCK: [2026-06-11 Thu 22:28]--[2026-06-11 Thu 23:28] =>  1:00
- State "DONE"       from "RESEARCH"   [2026-06-16 Tue 21:44]
:END:
[[https://crategus.com/books/cl-cffi-gtk/][cl-cffi-gtk API documentation]]
- [[http://www.crategus.com/books/atdoc/pages/atdoc.html][atdoc]]
- [[https://github.com/cl-doc-systems][cl-doc-systems]]
- see [[info:emacs#Enriched text][enriched]]
- [[info:elisp#Display Property][elisp#Display Property]]
:outline:
- templates (one file each):
  - symbol (most primitive) - heading
  - package
  - components
    - file-component
    - mod-component
  - system
  - project
:end:
- not much out there, start from scratch with emacs info-mode..
* TBD fobs
:PROPERTIES:
:ID:       f612c2b3-9ebd-413a-a938-1084ce88e473
:CREATED:  <2026-03-08 Sun 21:45>
:END:
:LOGBOOK:
- State "TBD"        from              [2026-03-08 Sun 21:45]
:END:
federated objects - stored-objects shared with DHT peers
* TODO linux firmware investigation
:PROPERTIES:
:ID:       b2043211-a69c-4d0d-b7a1-87822d5628ec
:CREATED:  <2024-08-30 Fri 19:47>
:END:
:LOGBOOK:
- State "TODO"       from              [2023-12-03 Sun 00:11]
- Refiled on [2026-06-05 Fri 16:00]
:END:
NVMe char/block devices, initrd,initramfs (ramdisk)
https://yuhei1-horibe.medium.com/booting-linux-with-ramdisk-f6f2d59780dc
https://www.gibbard.me/linux_initramfs_initrd/
https://docs.kernel.org/admin-guide/blockdev/ramdisk.html
https://www.oreilly.com/library/view/linux-device-drivers/0596005903/ch15.html
https://www.oreilly.com/library/view/linux-device-drivers/0596005903/ch16.html
https://www.oreilly.com/library/view/linux-device-drivers/0596000081/ch12s06.html
https://lpc.events/event/11/contributions/989/attachments/747/1723/lpc-2021-building-a-fast-passthru.pdf
https://github.com/espoal/uring_examples/blob/main/examples/nvme/src/main.rs
https://itnext.io/modern-storage-is-plenty-fast-it-is-the-apis-that-are-bad-6a68319fbc1a
https://docs.rs/glommio/latest/glommio/index.html
* pipelines vs runstreams
:PROPERTIES:
:ID:       dcdaa8e6-aa19-4bca-8841-d667796f8c3f
:CREATED:  <2026-04-19 Sun 17:33>
:END:
:LOGBOOK:
- Refiled on [2026-06-05 Fri 16:08]
:END:
- steal the artemis term
- against UNIX pipelines (proc | pipe | proc)
* graphviz stuff
:PROPERTIES:
:ID:       90b4eaa4-4dfe-43f9-aae2-5196343c5922
:END:
:LOGBOOK:
- State "NOTE"       from              [2024-04-06 Sat 14:35]
- Refiled on [2026-06-05 Fri 16:10]
:END:
- check out graphviz-dot-mode.el
https://graphviz.org/doc/info/lang.html
https://graphs.grevian.org/
* mailman
:PROPERTIES:
:ID:       cf47e740-33d4-44b5-aef5-fddaa83dc9d4
:END:
:LOGBOOK:
- Refiled on [2026-06-05 Fri 16:12]
:END:
- State "NOTE"       from              [2023-12-02 Sat 23:35]
#+begin_src rust :eval no
  let client = Client::new()
  //    .credentials(Credentials::bearer("hackme")
    .connect("https://mail.compiler.company:8080")
    .await
    .unwrap();
  println!(
    "{:?}",
    client
      .email_query(
        Filter::and([email::query::Filter::has_keyword("$draft")]).into(),
        [email::query::Comparator::from()].into()
      )
      .await
      .unwrap()
      .take_ids()
  );
  // Query mailboxes to obtain Inbox and Trash folder id
  let inbox_id = client
    .mailbox_query(
      mailbox::query::Filter::role(mailbox::Role::Inbox).into(),
      None::<Vec<_>>,
    )
    .await
    .unwrap()
    .take_ids()
    .pop()
    .unwrap();
  let trash_id = client
    .mailbox_query(
      mailbox::query::Filter::role(mailbox::Role::Trash).into(),
      None::<Vec<_>>,
    )
    .await
    .unwrap()
    .take_ids()
    .pop()
    .unwrap();

  println!("Inbox: {:?}", inbox_id);
  println!("Trash: {:?}", trash_id);

#+end_src

* mail init
:PROPERTIES:
:ID:       bc132221-c0de-4e1e-a801-2b63537ef56e
:HEADER-ARGS: :eval no
:END:
:LOGBOOK:
- Refiled on [2026-06-05 Fri 16:22]
:END:
- State "NOTE"       from              [2023-11-30 Thu 14:35]
#+begin_src lisp
  (list
   (ql:quickload :sxql)
   (ql:quickload :std)
   (ql:quickload :dbi))
#+end_src

#+RESULTS:
| :sxql |
| :std  |
| :dbi  |

#+begin_src lisp :tangle stalwart.lisp :results silent
  ;;; stalwart.lisp --- stalwart-mail utils

  ;;; Code:
  (defpackage :stalwart
    (:use :cl :std :sxql :dbi)
    (:export 
     :init-db :delete-db :init-tables :*db-path*
     :create-accounts-table :create-group-members-table :create-emails-table
     :create-user :create-group :add-alias :add-to-mailing-list :add-to-group))

  (in-package :stalwart)

  ;; #P"/opt/stalwart-mail/data/accounts.sqlite3"
  (defparameter *db-path* #P"accounts.sqlite3")
  (defvar *connection* (init-db))

  ;; FIXME: set defaults correctly, active = 1, quota = 0
  (defun create-accounts-table ()
    (create-table :accounts
          ((name :type 'text
                 :primary-key t)
           (secret :type 'text)
           (description :type 'text)
           (type :type 'text)
           (quota :type 'integer)
           (active :type 'boolean))))

  (defun create-group-members-table ()
    (create-table :group_members
        ((name :type 'text
               :not-null t)
         (member_of :type 'text
                    :not-null t))
      (primary-key '(:name :member_of))))

  (defun create-emails-table ()
    (create-table :emails
        ((name :type 'text
               :not-null t)
         (address :type 'text
                  :not-null t)
         (type :type 'text))
      (primary-key '(:name :address))))

  ;; (insert-user "ellis" "hackme" "r w")
  (defun insert-user (name secret full-name)
    (do-sql *connection*
      "INSERT INTO accounts (name, secret, description, type, quota, active) VALUES (?,?,?,'individual',0,1)"
      (list name secret full-name)))

  ;; (insert-group "mlist" "desc")
  (defun insert-group (name description)
    (do-sql *connection*
      "INSERT INTO accounts (name, description, type) VALUES (?,?,'group')"
      (list name description)))

  ;; (insert-email "ellis" "ellis@c.c")
  (defun insert-email (name address &optional (type "primary"))
    (do-sql *connection*
      "INSERT INTO emails (name, address, type) VALUES (?,?,?)"
      (list name address type)))

  ;; (insert-group-member "ellis" "superusers")
  (defun insert-group-member (name group)
    (do-sql
      ,*connection*
      "INSERT INTO group_members (name, member_of) VALUES (?,?)"
      (list name group)))

  ;; (create-user "ellis" "ellis@c.c" "hackme" "r w" t)
  (defun create-user (name address secret full-name admin)
    (list
     (insert-user name secret full-name)
     (insert-email name address)
     (when admin (insert-group-member name "superusers"))))

  ;; (defun delete-user (name))

  ;; (add-alias "ellis" "el@c.c")
  (defun add-alias (name alias)
    (insert-email name alias "alias"))

  ;; (add-to-mailing-list "ellis@c.c" "list@c.c")
  (defun add-to-mailing-list (name mlist)
    (insert-email name mlist "list"))

  ;; (add-to-group "ellis" "groupies")
  (defun add-to-group (name group)
    (insert-group-member name group))

  ;; (create-group "list@c.c" "foobar")
  (defun create-group (name description)
    (insert-group name description))

  ;; (init-db)
  (defun init-db () (setq *connection* (dbi:connect :sqlite3 :database-name *db-path*)))

  (defun init-tables ()
    (do-sql *connection* (yield (create-accounts-table)))
    (do-sql *connection* (yield (create-emails-table)))
    (do-sql *connection* (yield (create-group-members-table))))

  (defun delete-db () (delete-file *db-path*))
#+end_src

#+name init-accounts-db
#+begin_src lisp
  (use-package :stalwart)
  (init-db)
  (init-tables)
  (create-user "ellis" "ellis@compiler.company" "hackme" "rw" t)
  (create-group "homies" "all da homies")
  (add-alias "ellis" "other@compiler.company")
  (add-to-mailing-list "ellis" "info@compiler.company")
  (add-to-group "ellis" "homies")
  (delete-db)
#+end_src

#+RESULTS:
: t

#+name run-live
#+begin_src lisp
  ;; (require :stalwart)
  ;; (use-package :stalwart)
  ;; (setq *db-path* #P"/opt/stalwart-mail/data/accounts.sqlite3")
  (init-db)
  (init-tables)
  (create-user "ellis" "ellis@compiler.company" "hackme" "Richard Westhaver" t)
  (create-group "dev" "developer group")
  (create-group "q" "query group")
  (add-alias "ellis" "richard@compiler.company")
  (add-to-mailing-list "ellis" "q@compiler.company")
  (add-to-mailing-list "ellis" "dev@compiler.company")
  (add-to-group "ellis" "dev")
  (add-to-group "ellis" "q")
  (delete-db)
#+end_src

#+RESULTS:
: t

* lisp makefiles
:PROPERTIES:
:ID:       5a2584a0-2c7c-42f3-8d2e-acecd99a5071
:HEADER-ARGS: :eval no
:END:
:LOGBOOK:
- State "NOTE"       from              [2023-08-12 Sat 18:30]
- Refiled on [2026-06-05 Fri 16:25]
:END:
#+begin_src makefile
  cover:$(src);$(LISP) --eval '(require :sb-cover)' \
          --eval '(declaim (optimize sb-cover:store-coverage-data))' \
          $(load)
#+end_src
* big data for small business
:PROPERTIES:
:ID:       39337cc2-770d-4977-b87c-990eecc5b20a
:CREATED:  <2025-01-17 Fri 15:54>
:END:
:LOGBOOK:
- Refiled on [2026-06-05 Fri 16:31]
:END:
* WGPU infinite canvas                                        :web:rust:wasm:
:PROPERTIES:
:ID:       1140bed7-7e99-4e27-b8e0-8fea2ba934a3
:CREATED:  <2025-01-17 Fri 15:54>
:END:
:LOGBOOK:
- Refiled on [2026-06-05 Fri 16:31]
:END:
[[https://github.com/gfx-rs/wgpu/tree/trunk/naga][wgpu/naga at trunk · gfx-rs/wgpu · GitHub]]
#+begin_src shell :eval no
  cargo install naga-cli
#+end_src

#+RESULTS:

[[https://wgpu.rs/][wgpu: portable graphics library for Rust]]
* apply constraint-based programming to planning ethos
:PROPERTIES:
:ID:       ec575bdd-9516-40d5-8d50-8a1769db0748
:CREATED:  <2025-01-17 Fri 15:54>
:END:
:LOGBOOK:
- Refiled on [2026-06-05 Fri 16:32]
:END:
https://en.wikipedia.org/wiki/Constraint_programming
* RDF, knowledge representations and relations
:PROPERTIES:
:ID:       228af016-57ee-4df9-a0dd-4edf6b11d9a6
:CREATED:  <2025-01-17 Fri 15:54>
:END:
:LOGBOOK:
- Refiled on [2026-06-05 Fri 16:32]
:END:
MADS/RDF - LoC
[[https://en.wikipedia.org/wiki/Metadata_Authority_Description_Schema#:~:text=MADS%20was%20originally%20formulated%20as,objects%20(RWOs)%20they%20describe.][Metadata Authority Description Schema - Wikipedia]]
[[https://en.wikipedia.org/wiki/Simple_Knowledge_Organization_System][Simple Knowledge Organization System - Wikipedia]]
[[https://en.wikipedia.org/wiki/RDF_Schema][RDF Schema - Wikipedia]]
[[https://www.w3.org/TR/swbp-skos-core-guide/][SKOS Core Guide]]
[[https://www.w3.org/TR/swbp-skos-core-spec/][SKOS Core Vocabulary Specification]]
[[https://www.w3.org/TR/swbp-thesaurus-pubguide/][Quick Guide to Publishing a Thesaurus on the Semantic Web]]
[[https://www.w3.org/2001/sw/BestPractices/][W3C Semantic Web Best Practices and Deployment Working Group]]
[[https://www.w3.org/2001/sw/][W3C Semantic Web Activity Homepage]]
[[https://www.dublincore.org/][DCMI: Home]]
* other types of dblocks
:PROPERTIES:
:LOCATION: ~/comp/core
:ID:       0ea1fe76-e4fa-4174-b582-5e2d681e1922
:CREATED:  <2025-01-17 Fri 15:54>
:END:
:LOGBOOK:
- Refiled on [2026-06-05 Fri 16:32]
:END:
org-invoice
propview
clocktable
columnview
[[https://github.com/org-roam/org-roam/issues/2251][Adding dynamic blocks to org-roam · Issue #2251 · org-roam/org-roam · GitHub]]
* RESEARCH message codec implementations
SCHEDULED: <2026-06-14 Sun>
:PROPERTIES:
:Effort:   8:00
:ID:       1f12485f-24eb-4267-ab6f-cbc56abd5191
:CREATED:  <2024-08-30 Fri 19:47>
:END:
:LOGBOOK:
- Refiled on [2026-06-08 Mon 20:21]
:END:
- [[https://github.com/klingtnet/rosc/blob/master/src/lib.rs][rosc/lib.rs at master · klingtnet/rosc · GitHub]]
  OSC 1.0 protocol
- [[https://docs.rs/tokio-util/0.6.9/tokio_util/codec/index.html][tokio_util::codec - Rust]]
- check out tokio_stream
  - [[https://docs.rs/tokio-stream/0.1.8/tokio_stream/struct.StreamMap.html][StreamMap in tokio_stream - Rust]]
- [[https://tokio.rs/tokio/tutorial/shared-state][Shared state | Tokio - An asynchronous Rust runtime]] - for registry
- [[https://tokio.rs/tokio/tutorial/channels][Channels | Tokio - An asynchronous Rust runtime]] - for daemons
- [[https://docs.rs/bytes/1.1.0/bytes/struct.Bytes.html][Bytes in bytes - Rust]]
- [[https://docs.rs/tokio-util/0.6.9/tokio_util/udp/index.html][tokio_util::udp - Rust]]
- TLV = Type Length Value
  used in meterpreter client protocol
  [[https://github.com/VakhoQ/tlv-encoder/][GitHub - VakhoQ/tlv-encoder: TLV (tag-length-value) communication protocol implementation in Java]]
  [[https://github.com/commiebstrd/rusterpreter][GitHub - commiebstrd/rusterpreter: Meterpreter compatible Rust binary and library]]
- [[https://github.com/rapid7/mettle][GitHub - rapid7/mettle: This is an implementation of a native-code Meterpreter, designed for portability, embeddability, and low resource utilization.]]
- QMP (QEMU)
- Podman API
- smalltalk
